### ISSUE TITLE
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found 

### ISSUE THREAD

**Issue by rashindrie** [alinlab/CSI#44]
Getting following error when running with 1 GPU:

```
> CUDA_VISIBLE_DEVICES=0 python  train.py --dataset imagenet  --model resnet18  --mode simclr_CSI --shift_trans_type rotation --batch_size 32 --one_class_idx 0
```

```
/home/rashindrie/.local/lib/python3.7/site-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
Traceback (most recent call last):
  File "train.py", line 7, in <module>
    from common.train import *
  File "/data/gpfs/projects/punim1193/tils_score_prediction/CSI/common/train.py", line 108, in <module>
    from torchlars import LARS
  File "/home/rashindrie/.local/lib/python3.7/site-packages/torchlars/__init__.py", line 2, in <module>
    from torchlars.lars import LARS
  File "/home/rashindrie/.local/lib/python3.7/site-packages/torchlars/lars.py", line 6, in <module>
    from torchlars._adaptive_lr import compute_adaptive_lr
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/rashindrie/.local/lib/python3.7/site-packages/torchlars/_adaptive_lr.cpython-37m-x86_64-linux-gnu.so)
```

Running with 2 GPUs give the following error:

```
> CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=4 train.py --dataset imagenet  --model resnet18  --mode simclr_CSI --shift_trans_type rotation --batch_size 32 --one_class_idx 0

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /tmp/torchelastic_jmq0lqp2/none_lvv336sz/attempt_1/0/error.json
INFO:torch.distributed.elastic.multiprocessing:Setting worker1 reply file to: /tmp/torchelastic_jmq0lqp2/none_lvv336sz/attempt_1/1/error.json
INFO:torch.distributed.elastic.multiprocessing:Setting worker2 reply file to: /tmp/torchelastic_jmq0lqp2/none_lvv336sz/attempt_1/2/error.json
INFO:torch.distributed.elastic.multiprocessing:Setting worker3 reply file to: /tmp/torchelastic_jmq0lqp2/none_lvv336sz/attempt_1/3/error.json

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -11) local_rank: 2 (pid: 235841) of binary: /home/rashindrie/.conda/envs/simclr/bin/python
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
INFO:torch.distributed.elastic.agent.server.api:[default] Worker group FAILED. 2/3 attempts left; will restart worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Stopping worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=2
  master_addr=127.0.0.1
  master_port=29500
  group_rank=0
  group_world_size=1
  local_ranks=[0, 1, 2, 3]
  role_ranks=[0, 1, 2, 3]
  global_ranks=[0, 1, 2, 3]
  role_world_sizes=[4, 4, 4, 4]
  global_world_sizes=[4, 4, 4, 4]

```

I have also attached a [list of packages in my conda environment](https://github.com/alinlab/CSI/files/7102113/conda_packages.txt). I created the conda env following package list at [SimCLR](https://github.com/sthalles/SimCLR/blob/master/env.yml).

Any help is appreciated.

Thank you!

**Comment by rashindrie** [comment]
I'll reply to my own question. 

While I was not able to fix the above issue in my conda env, I created a python virtual environment and tried running the above 2 commands. 

Both are working in the python venv.
